### ISSUE TITLE
Tags migration only installs 1/6

### ISSUE THREAD

**Issue by rosiel** [Islandora-Devops/migrate_7x_claw#38]
The tags migration will run but only install the first tag. No amount of rolling back/update will get it to install more than the first value.

I think it's due to the [Migrate Source CSV plugin](https://www.drupal.org/node/3060246) now installing the 3.x branch, which changed the syntax. Instead of `keys` we now specify a uniquely identifying column under the `id`  parameter. This seems to default to the first column, vid, which of course is the same for all tags so only one gets migrated.

PR to come.

**Comment by jordandukart** [comment]
Merged in the above, thanks @rosiel!
